# Generated by Django 3.2 on 2022-11-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('contact_type', models.CharField(choices=[('REQUEST', 'Submit a request'), ('CONTACT', 'Ask a question')], max_length=20)),
                ('description', models.TextField()),
                ('contact_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
